server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: p1

server:
  port: 8081

greeting.message: Hello World 8081!


---
spring:
  profiles: p2

server:
  port: 8082

greeting.message: Hello World 8082!


