info:
  component: Zuul server

server:
  port: 8765

zuul:
  routes:
    export-service:
      path: /simple-search/**
      serviceId: export

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false